spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: bizneswomen21
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

otp:
  expiration: 60000
  sendOtpLimit: 3
